### PR TITLE
fixed the build-error introduced by one of the last commits

### PR DESCRIPTION
**Pull request by egon0**

### CODE REVIEW

**Comment by aparcar** [comment]
isnt it better to call both babeld

**Comment by egon0** [comment]
dunno, just fixed the basic error to be able to build lime with lime-app again. as soon as any other package refers to the old plugin name (aka babel without d) it would break if we call both babeld.

**Comment by aparcar** [comment]
Please rename it to babeld, thats how the official package is called. Bad style to rename packages, but as it was broken likely nobody really used it anyway.
https://github.com/jech/babeld

**Comment by egon0** [comment]
done

**Pull request merged**
